Server:
  Host: "127.0.0.1"
  Port: 50051
DB:
  Cockroach:
    Hostname: "127.0.0.1"
    Port: 26257
    Username: "root"
    Databasename: "defaultdb"
S3:
  BucketPrefix: "test-bucket"
  Endpoint: "http://localhost:9000"
  Implementation: "MINIO"
EventNotifications:
  Backend: NATS
  NATS:
    Host: http://localhost:4222
    SubjectPrefix: "UPDATES"

