Server:
  Host: "127.0.0.1"
  Port: 50051
DB:
  Cockroach:
    Hostname: "127.0.0.1"
    Port: 26257
    Username: "root"
    Databasename: "defaultdb"
S3:
  BucketPrefix: "test-bucket"
  Endpoint: "http://localhost:9000"
  SkipDefaultCORSConfig: true
EventNotifications:
  Backend: Empty

