Server:
  Host: "127.0.0.1"
  Port: 50051
DB:
  Cockroach:
    Hostname: "cockroach"
    Port: 26257
    Username: "root"
    Databasename: "defaultdb"
  Postgres:
    Hostname: "postgres"
    Port: 5432
    Username: "testuser"
    Databasename: "testdb"
S3:
  BucketPrefix: "test-bucket"
  Endpoint: "http://minio:9000"
  SkipDefaultCORSConfig: true
EventNotifications:
  Backend: NATS
  NATS:
    URL: http://nats:4222
    SubjectPrefix: "UPDATES"


