Server:
  Host: "127.0.0.1"
  Port: 50051
DB:
  Host: "localhost"
  Port: 26257
  Username: "sciobjsdb"
  Name: "sciobjsdbtest"
OAuth2:
  UserInfoEndpoint: "https://keycloak.m1.k8s.computational.bio/auth/realms/SciObjsDB/protocol/openid-connect/userinfo"
S3:
  Bucket: "ScienceObjectsDBDev"

