Server:
  Host: "127.0.0.1"
  Port: 50051
DB:
  Host: "localhost"
  Port: 26257
  Name: "defaultdb"
  Username: "root"
S3:
  Bucket: "sciobjsdbbucket"
Streaming:
  Endpoint: http://localhost:9011
  Port: 9011
Test: true