version: '3'
services:
  devcontainer:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"  
    depends_on:
      - minioConf
      - cockroach
      - nats
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
  minioConf:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin; /usr/bin/mc rm -r --force myminio/test-bucket; /usr/bin/mc mb myminio/test-bucket; exit 0; "
  cockroach:
    image: cockroachdb/cockroach
    entrypoint: >
      /bin/sh -c "cockroach start-single-node --insecure --accept-sql-without-tls --store=type=mem,size=5GB"
    restart: always
    tmpfs:
      - /cockroach/cockroach-data
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
  nats:
    image: nats:alpine
    command: -js
    ports:
      - "4222:4222"
