Server:
  Host: "127.0.0.1"
  Port: 50051
DB:
  DatabaseType: CockroachDB
  Cockroach:
    Hostname: "cockroach"
    Port: 26257
    Username: "root"
    Databasename: "defaultdb"
S3:
  BucketPrefix: "test-bucket"
  Endpoint: "http://minio:9000"
  Implementation: "MINIO"
EventNotifications:
  Backend: NATS
  NATS:
    Host: http://nats:4222
    SubjectPrefix: "UPDATES"

