Server:
  Host: "127.0.0.1"
  Port: 50051
DB:
  Host: "localhost"
  Port: 26257
  Name: "defaultdb"
OAuth2:
  UserInfoEndpoint: "https://keycloak.m1.k8s.computational.bio/auth/realms/NFDI4Biodiversity/protocol/openid-connect/userinfo"
  RealmInfoEndpoint: "https://keycloak.m1.k8s.computational.bio/auth/realms/NFDI4Biodiversity"
S3:
  Bucket: "nfdi4biodivdevdata"