Server:
  Host: "0.0.0.0"
  Port: 50051
DB:
  DatabaseType: CockroachDB
  Cockroach:
    Hostname: "localhost"
    Port: 51337
    Username: "sciobjdsdbuser"
    Databasename: "sciobjsdb"
S3:
  BucketPrefix: "test-bucket"
  Endpoint: "http://localhost:9000"
  Implementation: "MINIO"
EventNotifications:
  Backend: NATS
  NATS:
    Host: http://localhost:4222
    SubjectPrefix: "UPDATES"

